### PR TITLE
adding CLI for scaffolding components with associated test files

### PR DESCRIPTION
**Pull request by gvn**

### CODE REVIEW

**Comment by gvn** [comment]
Closes #349

**Comment by gvn** [comment]
Ok, this almost works. I don't know why, but `npm scaffold` isn't being recognized when I run it. :rage1:

**Comment by k88hudson** [comment]
Cool! I'll give this a go tmr. did you do npm run scaffold?

**Comment by toolness** [comment]
Yeah, I keep forgetting to put `run` in there myself all the time. :)

This looks cool, @gvn can you add instructions for using this to the README?

**Comment by gvn** [comment]
Ok this new version should work with just `npm run scaffold`, which will interactively ask for a component name.

I'm trying to think of something better, and preferably shorter, than "scaffold" for the task name. :cake:

**Comment by toolness** [comment]
What about `npm run addtest`?

Just riffing off [`python manage.py startapp`](https://docs.djangoproject.com/en/1.7/ref/django-admin/#startapp-app-label-destination) :)

**Comment by gvn** [comment]
Sounds good! I just added some stuff to the README too.

**Pull request closed without merging**
