### PR TITLE
Change color of the homepage and about sidebar

### PR DESCRIPTION
**Pull request by iamjessklein**
change to blue! - this means I had to change the default sidebarColor
to blue.

### CODE REVIEW

**Comment by iamjessklein** [comment]
R? @ScottDowne  :facepunch:

**Comment by iamjessklein** [comment]
As long as @ScottDowne R+s me - we can close this as the icons are dealt with in #563 and #564

**Comment by ScottDowne** [comment]
R+ :heart: :tangerine: :full_moon: :four_leaf_clover: :dolphin: :cherry_blossom:

**Comment by iamjessklein** [comment]
:rainbow:

**Pull request merged**
