### PR TITLE
Fixes #483 - add video to Events page

### LINKED ISSUE #483: EVENTS: Video missing above the carousel
This was in the initial mock-ups. If this is still the plan, we will need to identify the video and place it.

### PR DESCRIPTION
**Pull request by mmmavis**

### CODE REVIEW

**Comment by toolness** [comment]
Hmm, I am confused by the inclusion of my commits in this PR, which appear to already be in the `develop` branch. Can you rebase the PR so it doesn't include them?

**Comment by mmmavis** [comment]
I *always always* run into issues when I `git rebase develop`.  Not sure why :(  But yea I think squash & rebase will help.

**Comment by mmmavis** [comment]
I think this is ready to be merged :+1: ? @toolness

**Comment by toolness** [comment]
> I *always always* run into issues when I `git rebase develop`.  Not sure why :(

Oh, um, I guess when I said "rebase" I actually meant "merge", sorry about that. Around 2010 we were given a training session by Scott Chacon (author of [Pro Git](http://git-scm.com/book/en/v2)) and he recommended using rebase very rarely, and preferring merge over it in almost all cases. In general I only use rebase when I *haven't* yet pushed it to a PR on GitHub, which is pretty much never these days...

Anyhow, so I should have said "merge"! Sorry about that.

(This PR looks good now BTW, thanks!)

**Pull request merged**
