### PR TITLE
Show multiple clubs in the same popup.

### LINKED ISSUE #360: Only one club in a given location is visible
As mentioned in https://github.com/mozilla/teach.webmaker.org/pull/354#issuecomment-84063644:

> I'm now realizing that if people *only* enter the city/country of their club, we're potentially going to have lots of pins stacked on top of each other--for example, if there are two webmaker clubs in brooklyn, then their pins will both likely be located in the center of brooklyn, directly on top of each other. Which means we need to either have a single marker for multiple webmaker clubs (showing all clubs in the location in the marker's popup), or "fake" things by artifically spreading the clubs a few hundred feet away from each other, or something else.

I tried adding two clubs with the same location name, "Mumbai", in the site and this is indeed the case. The clustering plugin does "cluster" them for as long as it can, which at least shows people that there are 2 clubs there, but once the user is maximally zoomed-in to the map, it only shows one of the markers.

### PR DESCRIPTION
**Pull request by toolness**
This attempts to fix #360 by allowing clubs with the same location/latlong to appear in the same popup.

I'm not happy with the CSS right now, but maybe that can be :boom: **MASSAGED** :boom: during #337?

### CODE REVIEW

**Comment by iamjessklein** [comment]
word choice! :-1:  
Agreed with the CSS concerns, particularly if there are like 10 orgs in one location. However, fantastic first step.

**Comment by toolness** [comment]
I recommend we wait until there actually *are* 10 orgs in one place :)

**Comment by iamjessklein** [comment]
Right, I am guessing that this probably isn't a concern for this release. cc/ @hannahkane

**Comment by hannahkane** [comment]
Agree that it's not a priority for initial release. Will be a good problem to have, when it arises. :)

**Comment by toolness** [comment]
Oh, I should also note that there is some repeated information here (the `Mumbai, Maharashtra, India` in the screenshot in the description). We can certainly remove repeated references of that but some design work would help.

**Comment by iamjessklein** [comment]
:+1:  agreed. I'll take a look at it today.

**Comment by ScottDowne** [comment]
Looks good to me, easy to walk through and tests pass.

Can we get a ticket filed for the design fixes for some time in the future?

**Comment by iamjessklein** [comment]
@ScottDowne design issue filed in #420

**Comment by jgmac1106** [comment]
When a club writes a long narrative description it messes up the map navigation. At least for me when I try to read the text box the map pushes down and the text box fades away.

**Comment by hannahkane** [comment]
Filed a separate issue for the bug. Thanks, @jgmac1106!

**Pull request merged**
