### PR TITLE
fix #272 - custom marker icon

### LINKED ISSUE #272: Change map marker on Clubs page
@alicoding mentioned that he needed an asset to change the map marker. I'm including the asset here: https://www.dropbox.com/s/q5e2a8qstswwd6u/map-marker.svg?dl=0

### PR DESCRIPTION
**Pull request by alicoding**
closes #272

### CODE REVIEW

**Comment by alicoding** [comment]
@toolness R?

**Comment by alicoding** [comment]
my test is going to fail here but I will try to fix that right now

**Comment by toolness** [comment]
hehe i was wondering about that :)

**Comment by toolness** [comment]
O yea! Nice.

**Pull request merged**
