### PR TITLE
fix expander a bit

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by toolness** [comment]
Er what things in particular is this supposed to fix? What functionality should I be verifying?

**Comment by ScottDowne** [comment]
Ah, sorry, it fixes: #784

**Comment by toolness** [comment]
aww the branch name :(

**Comment by ScottDowne** [comment]
haha, yeah

**Comment by toolness** [comment]
Hey want to take this opportunity to add unit tests to the expander too, fixing #698? :grin:

**Comment by ScottDowne** [comment]
I'm not super familiar with the test suite, so adding tests would not be quick.

**Comment by toolness** [comment]
o ok. :(

This looks good. I verified that everything is auto-expanded when JS is disabled, and both collapse/expend and keyboard accessibility work great when JS is enabled.

Out of curiosity, is there a reason you're calling the expand/collapse caret "ion"? It's kinda hard to search for since the word "function" includes it :)

Anyhow, thanks for the fix, merging now!

**Comment by ScottDowne** [comment]
ion is from http://ionicons.com/

Same icon used in webmaker app and the design team was moving towards them

ionicons creates the class.

That said, we could also add our own class along with ion, and when we reference it in css use our own class.

**Comment by toolness** [comment]
ohhh i see! got it, no worries.

**Pull request merged**
