### PR TITLE
Replacing lo-res assets with hi-res JPGs/SVGs Fixes #247

### LINKED ISSUE #247: Replace lo-res PNG logos with hi-res JPGs/PNGs/SVGs
From #118, we've now got the ol' SVG files and just need to replace them in the code:

- [x] Replace Hive logo in the footer with [Jess' SVG version on dropbox](https://www.dropbox.com/s/yz6ykagfaxr4va4/Hive_Network_logo.svg?dl=0)
- [x] Replace Mozilla wordmark in the footer with [Ricardo's SVG version on dropbox](https://dl.dropboxusercontent.com/u/43783651/Mozilla/mozilla-wordmark.svg)
- [x] Replace the Webmaker logo on the sidebar with [Cassie's hi-res JPG on dropbox](https://www.dropbox.com/sh/7nwgazjrlbh1x1l/AAAK-yKt6-DgCHQ_Yy2BjiSQa?dl=0) (she tried exporting as SVG but it looked wonky so we'll use a JPG)
- [X] Don't worry about the Maker Party logo as it's quite likely that it will be removed before launch.

### PR DESCRIPTION
**Pull request by vazquez**

### CODE REVIEW

**Comment by toolness** [comment]
Hey @vazquez, I just merged #250, which might conflict with your changes to `styles.less`... Just a heads-up!

**Comment by toolness** [comment]
Other than the potential conflict w/ #250, I think this looks good!

**Comment by vazquez** [comment]
I'll fix the conflict and merge Atul :) thanks!

**Comment by vazquez** [comment]
I messed things up. I'm creating a new PR. Closing this.

:cow: :star:

**Pull request closed without merging**
