### PR TITLE
Reorganize directories for JS

### PR DESCRIPTION
**Pull request by toolness**
This helps with #233 by making a `components` directory where we can put all our JSX components.

It also creates a separate JSX file for each page, which makes it easier for us to build out each page.

Things left to do:

- [X] ~~Put each component into its own individual directory with an `index.jsx` file.~~ We're not doing this, see discussion below for rationale.

### CODE REVIEW

**Comment by toolness** [comment]
Ok, so I'm now finding that having an `index.jsx` inside a directory doesn't work in as slick a way as `index.js` does. For instance, if you have `foo/index.jsx`, then `require('./foo')` won't work. After a bit of experimentation, I could find these solutions:

1. Explicitly refer to `index.jsx` when loading components (e.g. `require('./foo/index.jsx')`)
2. Name our index files `index.js` and **process all `.js` files as JSX**.  This has a number of drawbacks, though; for instance, syntax highlighters will get confused by the JSX in .js files, and we'll no longer have an easy way to tell our linter to ignore JSX.
3. Do further research into discovering whether there's a way to make `require('./foo')` properly load `index.jsx` files. (There might be some kind of third-party module or StackOverflow question out there that has solved it, which we simply haven't found yet.)
4. Don't put components in their own directories; keep them as their own files. We could then store their LESS in a *parallel* directory structure under the `less` directory. Thus, for instance, the LESS for the `foo` component might be stored in `less/components/foo.less`.

Any thoughts, @alicoding @gesa @mmmavis?

**Comment by toolness** [comment]
Any thoughts on my above comment, @alicoding @gesa @mmmavis?

**Comment by alicoding** [comment]
for `2` I'm using [Babel Sublime](https://github.com/babel/babel-sublime) which can deal with both `.jsx` and `.js` nicely for React, and we can update the build process similar to Kate's [React-Web-App](http://github.com/k88hudson/react-web-app) where webpack will process `.js` as `.jsx` as specified.

**Comment by toolness** [comment]
So on IRC @alicoding just pointed out that [mofo-example-app](https://github.com/MozillaFoundation/mofo-example-app) uses the `.jsx` extension explicitly. Given that precedent, we should probably just go with my option (4) above.

We should probably bring this issue up with mofo engineering at large, though, since it'd be nice for all projects to use the same convention, and there *are* some upsides to simply allowing JSX in all `.js` files.

**Comment by alicoding** [comment]
This is good to merge as long as Travis is happy and green :dancer:

**Pull request merged**
