### PR TITLE
Fixes #700 - added webmaker logo next to log in link

### LINKED ISSUE #700: Implement button design with Webmaker logo
This is to signal to the user the connection between Teach and Webmaker, in terms of authentication.

We decided to use option 3 here: https://redpen.io/vy733a8b80210605bd

The svg for the logomark is here: https://www.dropbox.com/s/4yndkmm0b1b92u3/logo-webmaker-flat.svg?dl=0

### PR DESCRIPTION
**Pull request by mmmavis**

### CODE REVIEW

**Comment by secretrobotron** [comment]
Can you rebase on https://github.com/mozilla/teach.webmaker.org/pull/626 ? That's where the new login work is done. @Pomax or @toolness can acknowledge.

**Comment by mmmavis** [comment]
done rebasing!

**Comment by secretrobotron** [comment]
@mmmavis nice. We just landed it on `develop` too.

**Comment by mmmavis** [comment]
Oh yea I saw the commit history and i rebased this PR with `develop` instead of https://github.com/mozilla/teach.webmaker.org/pull/626.  Hopefully this is good to merge? :ok_woman: ?

**Comment by secretrobotron** [comment]
@mmmavis mmmerge this :full_moon_with_face:

**Pull request merged**
