### PR TITLE
Add autocomplete to location field in add/edit clubs dialogs.

### LINKED ISSUE #353: Add autocomplete for the location field on the club form
As per the discussion in https://github.com/mozilla/teach.webmaker.org/pull/330#issuecomment-83788403, we need to implement autocomplete for the location field in the club form, perhaps using the [Google Places API](https://developers.google.com/maps/documentation/javascript/places) or something similar.

### PR DESCRIPTION
**Pull request by toolness**
This fixes #353.

TODOs:

- [x] Add tests.
- [x] The widget is technically disabled when the form is being submitted, but it isn't styled to *look* disabled, so we should change this.
- [ ] We're using `react-select`'s default CSS, which is subtly different from our CSS. Might want to get @vazquez to optimize it (we can file this as a separate issue if needed).
- [ ] There isn't an easy way to set `required` on the input field inside the `Select` component, so right now we just do a `window.alert` telling the user to fill out the location field. This is suboptimal, but we can file this as a separate issue if needed.

### CODE REVIEW

**Comment by toolness** [comment]
@alicoding do you think you have time to review this?

**Comment by alicoding** [comment]
@toolness I will not be able to review them in few hours, but if you can wait I will do them otherwise maybe @ScottDowne ?

**Comment by toolness** [comment]
I'm fine either way! @ScottDowne, if you're interested in reviewing this then you are welcome to assign the ticket to yourself and add the "In Progress" flag to this ticket. If you don't do that, then Ali, whenever you're free, feel free to do the same for yourself... thanks!

**Comment by ScottDowne** [comment]
I'll get to this later tonight :)

**Comment by ScottDowne** [comment]
Works well, tests pass and understanding the code was easy enough :)

**Pull request merged**
