### PR TITLE
Tag and release v0.0.2

### PR DESCRIPTION
**Pull request by toolness**
### Added
- During automated testing, the the entire site is now spidered for missing
  links. This uncovered a few broken links, which were fixed.
- Fixed many missing downloadable links on the Event Resources page.

### Changed
- Changed instances of "Mozilla Web Clubs" to "Mozilla Clubs".
- Every page on the site now has a unique `<title>` (previously, the
  title of every page was "Mozilla Learning").
- Removed tooltips from the sidebar.
- Made the sidebar color of pages more consistent.
- The "Legal" link in the footer now links to webmaker.org instead of
  mozilla.org.
- Minor typo fixes.
- The Clubs Toolkit page is now keyboard-accessible.
- The background color on the hero unit is now gray, which makes
  the text readable while the background image is still loading.
- The Web Literacy Map now uses bullet points instead of paragraphs.
- Browser-side tests are now automatically discovered by the test runner.

### CODE REVIEW

**Comment by toolness** [comment]
This PR consists of all the latest changes to the `develop` branch. So they've already been code-reviewed.

@hannahkane, @iamjessklein and @sabrinang, can you take a look at the site at https://teach.mofostaging.net/ and post here if everything looks OK to you? If it does, we'll merge this PR, which will automatically push all these changes to teach.mozilla.org.

(Note: teach.mofostaging.net technically contains the latest `develop` branch, not this PR... But hopefully the changes between the two are either nonexistent, or minor enough that it shouldn't matter for now. In the future we can change this.)

**Comment by hannahkane** [comment]
I'm +1, though I commented on #842 because I introduced a minor typo in that ticket.

**Comment by toolness** [comment]
Ok, hannah just said that the typo isn't a blocker for v0.0.2--so now just waiting on :+1: from @iamjessklein and @sabrinang to seal the deal!

**Comment by hannahkane** [comment]
@toolness - looking at the list, I don't think there's anything design-specific here that would block a release, so let's release this, and if @iamjessklein or @sabrinang want to address something, they can file a follow-up ticket. I don't want to go overboard on process. :)

**Comment by rossbruniges** [comment]
This is a great tidy up @toolness - good skills!!

**Comment by iamjessklein** [comment]
:+1: Ship it! :shipit:

**Pull request merged**
