### PR TITLE
Watch only .jpg .svg .png files in /img dir

### LINKED ISSUE #1019: development bug - npm start failing
When running `npm start` from the `develop` branch the following error occurred.

```shell
Fatal error while compiling index-static.bundle.js { [Error: EMFILE, open '/Users/mavisou/Development/teach-test/build/index-static/1.index-static.bundle.js']
  errno: 20,
  code: 'EMFILE',
  path: '/Users/mavisou/Development/teach-test/build/index-static/1.index-static.bundle.js' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: building index-static.bundle.js failed
    at failure (/Users/mavisou/Development/teach-test/lib/index-static-watcher.js:102:10)
    at IndexStaticWatcher.onBuild (/Users/mavisou/Development/teach-test/lib/index-static-watcher.js:59:14)
    at Tapable.<anonymous> (/Users/mavisou/Development/teach-test/node_modules/webpack/lib/Compiler.js:184:21)
    at Tapable.<anonymous> (/Users/mavisou/Development/teach-test/node_modules/webpack/lib/Compiler.js:263:19)
    at done (/Users/mavisou/Development/teach-test/node_modules/webpack/node_modules/async/lib/async.js:126:15)
    at /Users/mavisou/Development/teach-test/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at fs.js:944:21
    at Object.oncomplete (fs.js:107:15)
```

I *think* this is [the commit](https://github.com/mozilla/teach.webmaker.org/commit/8dca64c5e81e0627a5acce83143d4b916107718b) that introduced this issue.  Gonna see if I can fix this before @toolness is back from PTO :eyes:

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #1019

### CODE REVIEW

**Comment by toolness** [comment]
Should we only copy the images we watch, too? That way if we ever need to change the types of files we watch, it'll be evident b/c the files won't get copied into `dist` either... 

Also out of curiosity, are there non-svg/png/jpg files in your `images` directory? I'm curious what files are being watched/copied that is making your computer barf.

**Comment by mmmavis** [comment]
I ran this command [`find . -type f | perl -ne 'print $1 if m/\.([^.\/]+)$/' | sort -u`](http://stackoverflow.com/a/1842270) from the `/img` directory and this is the result
```bash
DS_Store
jpg
png
svg
```

**Comment by mmmavis** [comment]
> Should we only copy the images we watch, too? That way if we ever need to change the types of files we watch, it'll be evident b/c the files won't get copied into `dist` either... 

Yes, and I just updated the PR.  :smiley_cat:

**Comment by toolness** [comment]
awsm this looks great, thanks mavis!

**Pull request merged**
