### PR TITLE
removed button on home page

### PR DESCRIPTION
**Pull request by iamjessklein**
Fixes https://github.com/mozilla/teach.webmaker.org/issues/746

### CODE REVIEW

**Comment by iamjessklein** [comment]
hey @toolness can you take a :eyes: at this PR?

**Comment by toolness** [comment]
Yeah, it looks like this PR and my own #762 are failing for the same [reasons](https://travis-ci.org/mozilla/teach.webmaker.org/builds/59403096#L392-L404), which are unrelated to the actual code changes in the PRs:

```
[14:13:52] Error in plugin 'gulp-less'
Message:
    '../node_modules/react-select/less/default.less' wasn't found. Tried - /home/travis/build/mozilla/teach.webmaker.org/node_modules/react-select/less/default.less,/home/travis/build/mozilla/teach.webmaker.org/node_modules/react-select/less/default.less,../node_modules/react-select/less/default.less in file /home/travis/build/mozilla/teach.webmaker.org/less/index.less line no. 6
Details:
    type: File
    filename: /home/travis/build/mozilla/teach.webmaker.org/less/index.less
    index: 108
    line: 6
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: @import "pages/index";,@import "../node_modules/react-select/less/default.less";,@import (less) "../node_modules/webmaker-app-icons/css/ionicons.css";
    lineNumber: 6
    fileName: /home/travis/build/mozilla/teach.webmaker.org/less/index.less
```

It looks like `gulp-less` was upgraded to 3.0.3 yesterday, and since our `package.json` isn't strict about what version it's using, my guess is that it's using the latest version of gulp-less which somehow broke things. I'm looking into it now.

**Comment by toolness** [comment]
Hmm, upgrading my own machine to `gulp-less` 3.0.3 doesn't seem to reproduce the problem.

**Comment by toolness** [comment]
Oh, it looks like the problem is with `react-select`--version 0.4.7 was released 5 hours ago. The bug has already been filed at https://github.com/JedWatson/react-select/issues/139.

For now we can fix by forcing the use of 0.4.6.

**Comment by toolness** [comment]
Ok, I think I fixed things in af25115156a69c1d62bc203ef1b29a411712a305, if you rebase/merge the latest develop branch, hopefully things should work!

**Pull request merged**
