### PR TITLE
Tag and release v0.0.12

### PR DESCRIPTION
**Pull request by mmmavis**
### Added
- A "Maker Party 2015 Activities" page has been added. Check out some fun
  sample activities we put together.
- SVG images are now optimized by SVGO. SVGO will fail if it encounters a SVG
  that was exported with the "Preserve Illustrator Editing Capabilities" option
  checked.

### Changed
- Refreshed the Events page to include a link to sample Maker Party activities
  as well as three Maker Party case studies.

### CODE REVIEW

**Comment by mmmavis** [comment]
@hannahkane review please :bowtie:

**Comment by hannahkane** [comment]
+1

As discussed, I'll likely file a follow-up ticket about the post-form submission success message on the MP page, but this is good to go.

Great work!

**Comment by mmmavis** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers:

**Comment by hannahkane** [comment]
Hooray!

**Pull request merged**
