### PR TITLE
#510 MOBILE: In navigation the Clubs Toolkit is hidden

### PR DESCRIPTION
**Pull request by jamieleung**

### CODE REVIEW

**Comment by jamieleung** [comment]
Apologies I had a little trouble with my git commits, I've finally sorted it now with the most recent commit being `bd98859` :)

**Comment by ScottDowne** [comment]
The commit message of this bug sounds like the same bug as https://github.com/mozilla/teach.webmaker.org/pull/521

**Comment by toolness** [comment]
Thanks @jamieleung! I agree with @ScottDowne though, this does seem to be trying to tackle the same kind of thing as PR #521, only with a different approach? I haven't looked closely at the CSS of either PR yet but at first glance I do like that #521 removes code and potentially reduces complexity, while this one adds code and potentially increases complexity :) I'd leave it to @vazquez for an expert opinion on the matter, though!

**Comment by vazquez** [comment]
Hey @jamieleung :) I love seeing you contributing! :heart: 

I think I would prefer to merge in @ScottDowne's PR #521 just for the fact that 521 also reduces unneeded complexity in the CSS. Your approach works perfectly fine, but if there is an opportunity to make the CSS simpler, then I'm all for it. Sound good?

**Comment by jamieleung** [comment]
Hey @vazquez and @toolness, Thanks for your kind words. It's great to contribute on this project, especially as I currently work as a Digital Designer for a social enterprise design agency working for for charities & pro-social organisations. :smiley: 

I too agree with @ScottDowne's reduction in complexity, go for the merge :+1:

**Comment by toolness** [comment]
Ok, I just merged #521 so I'm closing this one now. Thanks though for your contribution @jamieleung, if there are any other good first bugs for you to take, we will try to let you know about them--in the meantime feel free to issue PR's for anything you want to take on :)

**Pull request closed without merging**
