### PR TITLE
Tag and release v0.0.11

### PR DESCRIPTION
**Pull request by mmmavis**
### Added
- Added "Pledge to Teach" CTA button on the Home page to encourage
  site visitors to sign up the mentor mailing list.
- Introduced a new modal dialog design - folded corner. This style has
  been applied to the "Pledge to Teach" modal dialog.
- E-mail Regex validator has been moved to a newly created file `lib/util.js`.
- Added environment variables `PLEDGE_MAILINGLIST_URL`
  and `PLEDGE_MAILINGLIST_PRIVACY_NAME`.

### Changed
- The "Naming" subsection in the "Name and Brand Your Club" section on
  the Clubs Toolkit page has been updated.
- Fixed download links for assets on the Events Resources page. They now
  point to https://stuff.webmaker.org.

### CODE REVIEW

**Comment by toolness** [comment]
Woot!

**Comment by mmmavis** [comment]
@hannahkane review please? :hamster: 

(The 2 Maker Party related pages will be in the next release :wink: Just wanted to get the Pledge CTA out first)

**Comment by hannahkane** [comment]
+1

**Comment by mmmavis** [comment]
@toolness weird Travis is failing https://travis-ci.org/mozilla/teach.webmaker.org/builds/69054370#L672 slow network problem?

**Comment by mmmavis** [comment]
Weird that I don't have that "refresh" looking button when I viewed that page, even when I logged in with my GitHub account.


Screencap taken by @Pomax and I had him to restart the build for me! (Thanks Pomax!)

**Comment by mmmavis** [comment]
yay Travis gave the OK :tada:

**Comment by toolness** [comment]
Wooot! Congrats on your second release!

**Comment by hannahkane** [comment]
Awsm! Congrats, @mmmavis.

@ldecoursy - heads up, the pledge is now live. Let me know if you want to coordinate about follow-up steps.

**Comment by chrislarry33** [comment]
Just walked through this....LOVE IT!

**Pull request merged**
