### PR TITLE
update bottom cta component and use it in a new stub page for clubs tool...

### PR DESCRIPTION
**Pull request by ScottDowne**
...kit

### CODE REVIEW

**Comment by ScottDowne** [comment]
This just starts the toolkit page and makes the bottom cta bit in clubs something I can reuse.

I just need to make the expander thingy from web-lit something I can reuse and then use it here too.

**Comment by ScottDowne** [comment]
Scratch that, this is much closer to done.

What is left:
- [ ] Figure out color codes for expander menu in this page.
- [ ] Plug the "Add you map to the club" button into something. This might be tricky because it's not on the same page, so we need to wire it up somehow.

**Comment by ScottDowne** [comment]
Ugh, wish travis was faster. I'll fix tomorrow.

**Comment by vazquez** [comment]
:+1:

**Comment by ScottDowne** [comment]
Fixes #255

**Comment by vazquez** [comment]
I opened a PR on your branch with my changes. Looking good man :+1: 

https://github.com/ScottDowne/teach.webmaker.org/pull/3

**Pull request merged**
