### PR TITLE
Fixes #956 - copy changes on /home and /about

### LINKED ISSUE #956: Copy change on homepage and /about
We need to be consistent with our usage of "The Mozilla Learning Network" as opposed to "Mozilla Learning Networks".

On homepage:
 * Second sentence of lead paragraph should read "The Mozilla Learning Network offers programs..."

On About page:
 * Header: "About the Mozilla Learning Network"
 * Intro paragraph: "We want more people to see themselves as citizens of the web. The Mozilla Learning Network offers programs..."

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #956 .

### CODE REVIEW

**Comment by toolness** [comment]
According to #956, I think you need to also change "Networks" to singular, so it reads as "The Mozilla Learning Network" rather than "The Mozilla Learning Networks"?

Also, the lowercase "the" in the header looks weird to me even though it's what hannah wrote in #956. I posted a comment at https://github.com/mozilla/teach.webmaker.org/issues/956#issuecomment-107897321 to verify that.

**Comment by toolness** [comment]
Update: looks like we will [keep "the" lowercased](https://github.com/mozilla/teach.webmaker.org/issues/956#issuecomment-107976904), so don't worry about changing that!

**Comment by mmmavis** [comment]
Good eye - sorry apparently I'm not good at spotting trivial copy changes :stuck_out_tongue: 
PR updated again!

**Comment by toolness** [comment]
Woot thanks!

**Pull request merged**
