### PR TITLE
Added sample Webmaker activity to Tools page

### LINKED ISSUE #1105: Webmaker can have an associated activity on tools page
https://teach.mozilla.org/tools/ has a Webmaker link, but no activity. Could use mozilla.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html now.

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #1105

### CODE REVIEW

**Comment by mmmavis** [comment]
Travis build failed.  Will look at the log tmr morning.

**Comment by toolness** [comment]
Hmm looks like it doesn't have anything to do w/ your PR...

```
npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!

npm ERR! peerinvalid Peer mocha-phantomjs@3.5.4 wants phantomjs@1.9.1 - 1.9.7-15
```

Weird, I'll look into this!

**Comment by mmmavis** [comment]
yay Travis is happy

**Comment by mmmavis** [comment]
For some reason this didn't get merged properly into `develop` (commit not showing in https://github.com/mozilla/teach.webmaker.org/commits/develop).  I just reverted this PR and I'm going to reissue an new one.

**Pull request merged**
