### PR TITLE
Created pages directory to separate top level pages from components

### PR DESCRIPTION
**Pull request by k88hudson**
I know *technically* there is no distinction between pages and components in React, but I personally I think making the distinction is worth doing. IMO It helps reveal what components are available and prevents duplication of work.

Note that I haven't reorganized the LESS accordingly, I figured I would submit this PR first to see what your thoughts are

### CODE REVIEW

**Comment by k88hudson** [comment]
@toolness what do you think?

**Comment by toolness** [comment]
Oh, that's funny, we actually originally planned to do this a little while ago but I got [cold feet](https://github.com/mozilla/teach.webmaker.org/issues/233#issuecomment-78264925)--I think now that the codebase has matured, though, it is probably a good idea indeed!

**Comment by k88hudson** [comment]
Hahaha! That's pretty funny @toolness

**Comment by gesa** [comment]
@k88hudson I hadn't noticed you opened this PR, but it definitely addresses 50% of #350. Feel free to add the Less portion to this PR, but if you chose not to that's fine and we can just leave #350 open.

**Comment by k88hudson** [comment]
@gesa I'd prefer to merge quickly after rebasing, feel free to address less separately

**Comment by k88hudson** [comment]
@gesa ok rebase is done. want to review?

**Comment by toolness** [comment]
Woo this looks good to me so far! @gesa if you are happy w/ things feel free to merge!

**Comment by gesa** [comment]
I am thrilled, R+

**Pull request merged**
