### PR TITLE
replaced listen icon with smaller line weight version

### LINKED ISSUE #488: TEACH LIKE MOZILLA: Listen Icon - fix line weight
Clean up the listen icon to unify the line width to match "say hello" icon

screen shot 2015-03-31 at 6 16 13 pm

### PR DESCRIPTION
**Pull request by iamjessklein**
Fixes #488

### CODE REVIEW

**Comment by iamjessklein** [comment]
@ScottDowne please take a :eyes: when you have a chance to R :question:

**Comment by ScottDowne** [comment]
It looks much smaller than the other icons now.
icons

**Comment by ScottDowne** [comment]
I think the listen icon needs to be cropped?

**Comment by iamjessklein** [comment]
I just tried cropping and then the line weight decreased, asking @sabrinang to re-export

**Comment by ScottDowne** [comment]
R+ :four_leaf_clover: :four_leaf_clover: :four_leaf_clover:

**Pull request merged**
