### PR TITLE
Auto-discover browser tests.

### PR DESCRIPTION
**Pull request by toolness**
This uses webpack's [`val-loader` plugin](https://github.com/webpack/val-loader) to dynamically find browser-side tests. As such, it makes adding new browser-side tests as easy as writing server-side ones, and moves us further towards implementing #332, too.

Note that we actually stopped running the `routes.test.jsx` test in #325 but I failed to actually remove it from the repository, so I've done that in this PR.

@k88hudson can you take a look at this?

### CODE REVIEW

**Comment by toolness** [comment]
Hmm I think k88hudson is pretty busy. @mmmavis, do you want to take a look at this? I think it could help familiarize you with the workings of webpack a bit.

**Comment by k88hudson** [comment]
Oops sorry! Missed this ping, I'll take a look asap



— K

**Comment by k88hudson** [comment]
Oops sorry! Missed this ping, I'll take a look asap

**Comment by k88hudson** [comment]
This is fine, although you could also take advantage of dynamic requires http://webpack.github.io/docs/context.html

**Comment by toolness** [comment]
Cool thanks!

**Pull request merged**
