### PR TITLE
(WIP) Fixes #706 - added links to Events Resources page

### LINKED ISSUE #706: Add links to Events Resources page
THE BASICS
* Make Some Gear: 
  * "logo" should link to eps logo file
  * "shirts" in "what your shirts could look like" should link to https://party.webmaker.org/img/makerparty_tshirtpreview.jpg (let's move that file to teach, though)
  * "this activity" should link to https://tbx.makes.org/thimble/stencil-a-tshirt
  * "certificates" should link to https://makerparty2014.makes.org/thimble/LTEzNDM3NTAxNDQ=/maker-party-love-bomb
* All About The Wifi:
  * "activities that require no Internet access" should link to https://keyboardkat.makes.org/thimble/LTIxMDA3NTY0ODA=/lofi-nofi-teaching-kit

BEFORE EVENT
 * Add Your Event to the Map:
  * link "our global map" to https://events.webmaker.org
 * Recruit Mentors:
  * "Sample Volunteer Package" should link to https://party.webmaker.org/party-resources/pdf/Sample_Volunteer_Package.pdf (let's host that on Teach, though)
 * Promote Your Event:
  * "poster" should link to https://techkim.makes.org/thimble/maker-party-movie-poster
 * Press:
  * "Maker Party Press Kit" should link to https://wiki.mozilla.org/Maker_Party/Communications/Press_Kit
  * "social media toolkit" should link to https://wiki.mozilla.org/Maker_Party/Communications/Social_Media_Guide
  * "#makerparty" should link to https://twitter.com/search?f=realtime&q=%23makerparty

DURING EVENT
 * Design a Fun Experience:
  * "spectrogram" should link to https://mozteach.makes.org/thimble/how-to-run-a-spectrogram-icebreaker
 * Set-up:
  * "event checklist" should link to https://party.webmaker.org/party-resources/pdf/Event_Set_Up_Checklist.pdf (let's host that on Teach) 
 * Activities:
  * "some of ours" should link to /activities
 * Documentation:
  * "#makerparty" should link to https://twitter.com/search?f=realtime&q=%23makerparty
 * Wrap-up:
  * "event take down checklist" should link to https://party.webmaker.org/party-resources/pdf/Event_Take_Down_Checklist.pdf (let's host on Teach)

AFTER EVENT
 * Share What You Learned:
  * "#makerparty" should link to https://twitter.com/search?f=realtime&q=%23makerparty
  * "sample guidelines" should link to https://party.webmaker.org/party-resources/pdf/Sample_Blog_Post_Guidelines.pdf (let's host on Teach)
 * Thank You's:
  * "Send a heartfelt "Thank You!"" should link to https://party.webmaker.org/party-resources/pdf/Sample_Thank_You_Letters.pdf (host on Teach)

### PR DESCRIPTION
**Pull request by mmmavis**
WIP, this fixes #706 

Currently fixing
```
Error: Requested Range Not Satisfiable
    at SendStream.error (/Users/mavisou/Development/teach.webmaker.org/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/index.js:245:16)
    at SendStream.send (/Users/mavisou/Development/teach.webmaker.org/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/index.js:540:19)
    at onstat (/Users/mavisou/Development/teach.webmaker.org/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/index.js:600:10)
    at Object.oncomplete (fs.js:107:15)
```
when loading PDFs

### CODE REVIEW

**Comment by mmmavis** [comment]
Not sure what went wrong, is it client failed to load or server failed to serve?

Below are the console errors when I accessed one of the PDFs via `http://localhost:8008/event-resources/Event_Set_Up_Checklist.pdf`
```
"Error: Illegal character: 41" pdf.worker.js:250:4
"Lexer_getObj@resource://pdf.js/build/pdf.worker.js:30281:11
Parser_refill@resource://pdf.js/build/pdf.worker.js:29476:19
Parser@resource://pdf.js/build/pdf.worker.js:29470:5
XRef_readXRef@resource://pdf.js/build/pdf.worker.js:3647:24
XRef_parse@resource://pdf.js/build/pdf.worker.js:3281:23
PDFDocument_setup@resource://pdf.js/build/pdf.worker.js:2476:7
PDFDocument_parse@resource://pdf.js/build/pdf.worker.js:2363:7
ensureHelper@resource://pdf.js/build/pdf.worker.js:1992:22
NetworkPdfManager_ensure/<@resource://pdf.js/build/pdf.worker.js:2006:7
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:1986:1
BasePdfManager_ensureDoc@resource://pdf.js/build/pdf.worker.js:1853:14
loadDocument/</<@resource://pdf.js/build/pdf.worker.js:33059:11
" pdf.worker.js:252:0
"Warning: Unsupported feature "unknown"" pdf.worker.js:235:4
"Warning: Unsupported feature "unknown"" pdf.js:235:4
"Warning: Indexing all PDF objects" pdf.worker.js:235:4
"PDF 556fcc11c5c73a248b6f7c0c2e207a3d [1.3 Mac OS X 10.8.5 Quartz PDFContext / Word] (PDF.js: 1.0.1040)" viewer.js:5393:0
"Error: Unknown block type in flate stream" pdf.worker.js:250:4
"FlateStream_readBlock@resource://pdf.js/build/pdf.worker.js:31170:7
DecodeStream_getByte@resource://pdf.js/build/pdf.worker.js:30736:9
Lexer_nextChar@resource://pdf.js/build/pdf.worker.js:29982:34
Lexer@resource://pdf.js/build/pdf.worker.js:29924:5
EvaluatorPreprocessor@resource://pdf.js/build/pdf.worker.js:12097:30
PartialEvaluator_getOperatorList@resource://pdf.js/build/pdf.worker.js:10608:26
Page_getOperatorList/pageListPromise<@resource://pdf.js/build/pdf.worker.js:2208:16
" pdf.worker.js:252:0
"Warning: Unsupported feature "unknown"" pdf.worker.js:235:4
"Warning: Unsupported feature "unknown"" pdf.js:235:4
```

I'll continue investigating it tomorrow.

cc @toolness :smile_cat: for tips and suggestions

**Comment by toolness** [comment]
Oh, it looks like this might be some kind of weird bug with `gulp-webserver`... I tried running both [`http-server`](https://www.npmjs.com/package/http-server) and `python -m SimpleHTTPServer` in the `dist` directory and the PDFs worked fine, and I fully expect things to work fine in production too. We should definitely file a bug about PDFs not loading properly with `gulp-webserver`, but I don't think it should block your work on this PR. As a workaround, can you use either `http-server` or `python -m SimpleHTTPServer` in the `dist` directory to verify those PDFs work for now?

**Comment by mmmavis** [comment]
@toolness 
so I did `http-server` in `dist` dir, visit `http://localhost:8080/event-resources/Event_Take_Down_Checklist.pdf` on my browser and I had no problem loading the PDF.  I guess we can merge this PR now?  I'll open a ticket for the `gupl-webserver` weirdness.

**Comment by toolness** [comment]
Looks good, thanks mavis!

**Pull request merged**
