### PR TITLE
Tag and release v0.0.7.

### PR DESCRIPTION
**Pull request by toolness**
### Added
- `srcset` attributes are now link-checked during automated testing.
- The dev version modal now *always* links to the latest release
  of the site, and potentially a link to the changes between the
  latest release and the current commit. It also links to
  `CONTRIBUTING.md`.
- A reference to novalidate.com has been added to `CONTRIBUTING.md`.

### Changed
- Homepage has been refreshed to better inform
  the site vistors of what they can do on the site.
- Homepage now shows the latest blog posts from
  https://blog.webmaker.org/.
- Various performance improvements to the manual test page have
  been added.

### CODE REVIEW

**Comment by toolness** [comment]
@hannahkane can you give this the go-ahead? Everything's live at https://teach.mofostaging.net/.

**Comment by hannahkane** [comment]
+1 w00t!

**Comment by toolness** [comment]
Hooray! I will push.

**Comment by toolness** [comment]
lol i missed the "comment" button and hit "close and comment" instead

**Comment by toolness** [comment]
:laughing:

**Comment by toolness** [comment]
:ship: https://github.com/mozilla/teach.webmaker.org/releases/tag/v0.0.7

**Pull request merged**
