### PR TITLE
Fixes #824, fixes #701 - sidebar colours

### LINKED ISSUE #701: @darkBlueSidebarColor is defined twice in variables.less
```less
@darkBlueSidebarColor: #5791CE;
@darkBlueSidebarColor: #2D4A8C;
```

Which one wins? We should probably remove whichever one we don't want...

### LINKED ISSUE #824: Event Resources page should be dark blue
Currently Events Landing Page and Event Resources page have different colours. All we need is to change the main colour of event resources page to be dark blue.

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #824, #812, and #701.

@vazquez review plz?  :hamster: :bowtie:

### CODE REVIEW

**Comment by mmmavis** [comment]
@vazquez could you double check https://github.com/mmmavis/teach.webmaker.org/blob/issue-824-fix-sidebar-colour/less/components/sidebar.less#L16-L40?  Wondering if `clubs-curriculum` and `clubs-toolkit` should be in `orangeSidebarColor` instead?

variables are defined here: https://github.com/mmmavis/teach.webmaker.org/blob/issue-824-fix-sidebar-colour/less/variables.less

**Comment by vazquez** [comment]
@mmmavis - Just double checked with @iamjessklein. 

You are right!  `clubs-curriculum` and `clubs-toolkit` should be same in `orangeSidebarColor`.

**Comment by vazquez** [comment]
R+ for this patch

**Comment by mmmavis** [comment]
qooooool :+1: thanks for double checking @vazquez ! will merge this PR after I hear back from Travis :)

**Pull request merged**
