### PR TITLE
Add Maker Party banner to Home page

### LINKED ISSUE #989: Implement Maker Party banner on homepage
Design is in #736

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #989

screen shot 2015-06-09 at 12 24 38 pm

### CODE REVIEW

**Comment by mmmavis** [comment]
@sabrinang 

In [your mockup](https://cloud.githubusercontent.com/assets/2492510/7832985/0309ec86-0418-11e5-88ac-61bb8e6d95fb.png) the MP banner illustration matches the width of the illustration below.  I tried to make them match but it looked kinda unbalanced (see below)

screen shot 2015-06-09 at 12 25 52 pm

...so I tweaked it and make sure their *height* match instead (see screenshot in this ticket's description).  Let me know if anything needs to be adjusted! :hamster:

**Comment by toolness** [comment]
This looks great overall, but I'm noticing on narrow (mobile-ish) viewports, the right side of the maker party logo is being clipped and a horizontal scrollbar is being placed at the bottom of the area, which allows the user to peruse the overflow:



(The screenshot is from Chrome but the bug happens in Firefox and IE11 too.)

Is there an easy way to have that logo scale to the width of its container for that type of viewport, so that there's no overflow?

**Comment by toolness** [comment]
Also, should this banner go live immediately, or should it show up only after a certain date?

**Comment by hannahkane** [comment]
@amirad - do you have a particular go-live date in mind for the MP banner, or can we do it whenever it's ready?

**Comment by amirad** [comment]
When it's ready please! The sooner the better so people can start preparing.

**Comment by toolness** [comment]
Ultra cool, that makes things easier for us!

**Comment by mmmavis** [comment]
@toolness thanks for spotting that out

I updated the PR again, adding
```CSS
img {
    max-width: 100%;
    height: auto;
}
```
to `.makerparty-banner img` should do the trick

**Comment by toolness** [comment]
Thanks, this looks much better!

There's just one stylistic thing that's sorta bugging me now... when the page width is between 480px and 768px, the Maker Party logo is stacked above the paragraph and horizontally centered, but the "Host a Maker Party" button is left-aligned:



That looks weird to me, maybe partly because the 3 buttons in the hero unit above it have 100% width. Once the width goes below 480px, the button's width becomes 100% and it looks great... I feel like using the same styling up to 768px might be good? it's just a nit and you can ignore it if you disagree. Feel free to merge!

**Comment by mmmavis** [comment]
tweaked!

**Pull request merged**
