### PR TITLE
Fix #512

### LINKED ISSUE #512: MOBILE: Image of globe should be centered
center globe image

### PR DESCRIPTION
**Pull request by iamjessklein**
I changed aligned the globe so that it’s centered on mobile.

### CODE REVIEW

**Comment by iamjessklein** [comment]
@ScottDowne can you take a look?

**Comment by ScottDowne** [comment]
This also centers all the activity kit thumbnails.

**Comment by ScottDowne** [comment]
Good opportunity here to show a bit about how react components work.

The Illustration component already has center as the default text-align: https://github.com/mozilla/teach.webmaker.org/blob/develop/less/components/illustration.less#L13

So you could get the same thing in your patch by removing the `text-align: left;` vs changing it to `text-align: center;`

**Comment by iamjessklein** [comment]
R? @ScottDowne

**Comment by ScottDowne** [comment]
Moved to #542

**Pull request closed without merging**
