### PR TITLE
Fixes #833 - interim solution to Clubs Curriculum & Activities

### LINKED ISSUE #833: Interim solution: add links to /clubs/curriculum from /activities
We've agreed that the distinction between Clubs Curriculum and Teaching Activities is not important to users. A more permanent solution is being designed in #830.

In the meantime, let's make the following changes:

* Remove the link to /clubs/curriculum from the sub-menu in the Mozilla Web Clubs nav item
screen shot 2015-04-28 at 9 07 43 am

* Instead, let's link to that curriculum by adding a new first item to the list of activities on /activities
  * Image: [the same one used on /clubs/curriculum]
  * Title: Web Literacy Basics (Teaching Kit) 
  * Level: Beginner
  * Developed by: Our seasoned educator community
  * Description: This six-part series helps learners become familiar with reading, writing and participating on the web. They'll discover the foundations of the web through production and collaboration. This is an ideal kit for Mozilla Clubs.

* Edit the content at the top of the /clubs/curriculum page to match this image:
screen shot 2015-04-28 at 9 13 04 am

* Remove the "What is Web Literacy" section from the bottom of the /clubs/curriculum page

* Change the path of the /clubs/curriculum page to /activities/web-lit-basics

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #833.

### CODE REVIEW

**Comment by mmmavis** [comment]
This PR includes
- content changes mentioned in https://github.com/mozilla/teach.webmaker.org/issues/833
- change `/clubs/curriculum` page to `/activities/web-lit-basics`
  - page redirect handled by `Router.Redirect`
  - renamed a few "clubs-curriculum" instances to "web-lit-basics" (file name changes, `pageClassName` change)
  - theme colour change: from orange to hot pink (what /activities page uses)

**Comment by toolness** [comment]
This is looking good! A few issues though:
* The `/clubs/curriculum` redirect is great--thanks for taking the initiative on that--but our static site generator is actually not generating `/clubs/curriculum/index.html`, which means that the link will still appear to be broken (the only reason it works on your dev system is probably b/c the old file at that location didn't get cleaned up--if you delete your `dist`  directory and then re-run `npm start`, you should see the problem). However, **I think we should file a separate issue for this** since it's kind of out of the scope of this particular issue.
* #833 says that the page's `<title>` and `<h1>` should be "Web Literacy Basics", but they're still "Clubs Curriculum".
* The `<h2>` that says "Web Literacy Basics" should actually say "Learning Objectives".

Let me know if I'm mistaken on any of these.

**Comment by mmmavis** [comment]
Hi @toolness thanks for reviewing

> * The `/clubs/curriculum` redirect is great--thanks for taking the initiative on that--but our static site generator is actually not generating `/clubs/curriculum/index.html`, which means that the link will still appear to be broken (the only reason it works on your dev system is probably b/c the old file at that location didn't get cleaned up--if you delete your `dist`  directory and then re-run `npm start`, you should see the problem). ~~However, I think we should file a separate issue for this since it's kind of out of the scope of this particular issue.~~ Actually, I just issued https://github.com/mmmavis/teach.webmaker.org/pull/2 against this PR!

Coooool I'll check out that PR soon.

> * #833 says that the page's `<title>` and `<h1>` should be "Web Literacy Basics", but they're still "Clubs Curriculum".
* The `<h2>` that says "Web Literacy Basics" should actually say "Learning Objectives".

Wooo~ nice catch.  Looks like I neglected some details on that screencap :grin:

**Comment by mmmavis** [comment]
@toolness hopefully this is ready to go :smiley: 
I
1) merged your PR
2) fixed merge conflicted (occurred in https://github.com/mmmavis/teach.webmaker.org/commit/11cc8d7a913f831905331908030982afa4cc7901#diff-7088e309fdcfeaac68bf87c584a4a7baL29)
3) made the copy changes you found

**Comment by toolness** [comment]
Awsm thanks mavis, this looks great!

**Pull request merged**
