### PR TITLE
 Modularize LESS code

### LINKED ISSUE #226: Modularize LESS code
Right now we've just got a big massive `styles.less` file that contains a ton of rules. Ali mentioned on today's stand that we might want to consider breaking it up into multiple files, where each file addresses the styling needs of a particular page or component.

I've already "modularized" the rules in `styles.less` to some extent by prefixing rules under the class of the part of the page they're in, e.g.:

```less
.sidebar {
  // All sidebar-related CSS rules go here...
}
```

However, I believe [Nicole Sullivan disagrees](http://www.stubbornella.org/content/2011/04/28/our-best-practices-are-killing-us/) with such things.

I'm not super experienced with refactoring CSS so would appreciate any feedback from @mmmavis, @gesa, @alicoding or anyone else who has dealt with large CSS codebases before!

### PR DESCRIPTION
**Pull request by gesa**
Fixes #226

### CODE REVIEW

**Comment by gesa** [comment]
This also begins to deal with the rest of #246 by adding bootstrap. (still need to delete it from `vendor` and use gulp to get it into `dist`)

**Comment by vazquez** [comment]
This is... this is so goddamn beautiful :cry:

**Comment by gesa** [comment]
lol :heart: :heart: :heart: let it never be said that i'm a generally disorganised person. (even if i'm not always organised in the "right" way :wink: )

**Comment by vazquez** [comment]
R+, super well structured :boom:

**Comment by toolness** [comment]
hooooraayyyyyyyyyyy! :+1:

**Pull request merged**
